#!/bin/bash

bib=''

printHelp() {
  echo "Usage: build [OPTION]...
Builds the first LaTeX (.tex) file found in this directory using xelatex.

Options
  -b, --bib       use biber to build the bibliography with the first .bcf file found in this directory
"
}

while [ $# -gt 0 ] ; do
  case $1 in
    -b | --bib) bib=1 ;;
    -h | --help) printHelp && exit 1
  esac
  shift
done

texFile=$(find . -type f -name "*.tex" -print -quit)

# Check if a .tex file was found
if ! [ -n "$texFile" ]; then
    echo "No .tex files found in this directory or its subdirectories."
    exit 1
fi

if [ $bib ]
then
  xelatex $texFile

  bibFile=$(find . -type f -name "*.bcf" -print -quit)

  # Check if a .bcf file was found
  if ! [ -n "$bibFile" ]; then
      echo "No .bcf files found in this directory or its subdirectories."
      exit 1
  fi

  biber $bibFile

  # Multiple runs of xelatex are required to pickup the bibliography changes.
  xelatex $texFile
  xelatex $texFile
else
  xelatex $texFile
fi

